### PR TITLE
Include sha in file info in diff

### PR DESCRIPTION
**Pull request by AdamStone**
I was glad to find a way to get a diff between a pair of commits using nodegit, but I also needed the sha of the changed files, so I had to make this modification.

### CODE REVIEW

**Comment by thisconnect** [comment]
Hi, thanks for your PR. Sorry I just saw that now somehow it did not pop up in my notifications. Before we put this into master I have a few questions. I would like to have similar options as the git cli version.

Why/how do you need per file based sha?

What would be the git cli equivalent of this?

One of the tests will show `sha: '0000000000000000000000000000000000000000'` when I log this in lib/diff.js . This is a test that shows an untracked file. Is this supposed to show up?

Maybe untracked should be ignored in as it would be in the cli version of git diff. I will check if there is a cli flag for including untracked files, otherwise I would change that.

Should NodeGit-kit provide some kind of callback that allows to return the data?

**Comment by AdamStone** [comment]
These are good questions.

> Why/how do you need per file based sha?

I had set up a git-related project in which I was storing and accessing all the git items by their sha. I was initially just using the Github API as the source of repo data, and the file data that comes back when comparing commits includes the sha of the blob representing that file in the second commit. https://developer.github.com/v3/repos/commits/#compare-two-commits

Now I'm trying to make the project compatible with both Nodegit and Github API as the interface to repo data, and lack of sha here was a problem. Making the above modification saved me from having to restructure my data model.

> What would be the git cli equivalent of this?

It looks like the default behavior of diff in the cli is to give abbreviated sha of both the before and after blobs associated with a given file, with the pattern `index <hash>..<hash> <mode>`. In my case I was only interested in the  "after" sha, and that is the behavior of Github API. Including the before as well might be worthwhile, but it looks like a more substantial change to the code would be needed to accomplish that. 

> One of the tests will show sha: '0000000000000000000000000000000000000000' when I log this in lib/diff.js . This is a test that shows an untracked file. Is this supposed to show up? Maybe untracked should be ignored in as it would be in the cli version of git diff. I will check if there is a cli flag for including untracked files, otherwise I would change that.

Not sure about untracked files, but when a diff includes additions or deletions, the cli output includes lines like
```
new file mode 100644
index 0000000..cc7b966
```
or 
```
deleted file mode 100644
index cc7b966..0000000
```
So it looks like all zeros is a standard way to represent sha for files that are outside the repo.

> Should NodeGit-kit provide some kind of callback that allows to return the data?

In my case I don't need the blob data at the time of getting the diff, so I'm just keeping track of the sha that changed and later using the sha to get the blob content through Nodegit like
```
      Nodegit.Repository.open('path/to/repo')
        .then(function(repo) {
          return repo.getBlob(sha);
        })
```
I guess a callback could make this slightly more convenient, but for this project at least I don't think I would use it anyway because it wouldn't generalize well to both Nodegit and Github API as repo sources.

**Comment by thisconnect** [comment]
Added sha1 and a test that just checks if sha is truthy  https://github.com/thisconnect/nodegit-kit/commit/2740a5b6b56da1aea50f9ce67ef1c05c137ba03c

GIT SCM has a reference to the first sha as sha1

> \<sha1\> is shown as all 0’s if a file is new on the filesystem and it is out of sync with the index.

https://git-scm.com/docs/git-diff

Thanks for the PR and sorry that it took so long

**Comment by AdamStone** [comment]
Thanks!

**Pull request merged**
